// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2GDWceFNX4gRadra2_Urslt79iRIn3-s',
    appId: '1:790141080371:web:a474365a0a6801bc9ba446',
    messagingSenderId: '790141080371',
    projectId: 'quon2-45c4f',
    authDomain: 'quon2-45c4f.firebaseapp.com',
    storageBucket: 'quon2-45c4f.appspot.com',
    measurementId: 'G-T4YMRK7P3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5WSwaiBCV-Q-oVF3KYG_35k7lWcyaos',
    appId: '1:790141080371:android:dd50dc55f40fb9389ba446',
    messagingSenderId: '790141080371',
    projectId: 'quon2-45c4f',
    storageBucket: 'quon2-45c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VFY8ZG23XxgUSEn5UVuAz5865Uhkm6o',
    appId: '1:790141080371:ios:1e116a749c47e6c19ba446',
    messagingSenderId: '790141080371',
    projectId: 'quon2-45c4f',
    storageBucket: 'quon2-45c4f.appspot.com',
    iosBundleId: 'com.example.quon2',
  );
}
